In [15]:
import numpy as np
#zadanie 1
vector = np.array([1, 4, 5, 6, 2, 1, 5, 6, 7, 0])
print(vector)

[1 4 5 6 2 1 5 6 7 0]


In [16]:
vector2 = np.delete(vector, 5)
print(vector2)

[1 4 5 6 2 5 6 7 0]


In [17]:
vector3 = np.insert(vector, 10, 8)
print(vector3)

[1 4 5 6 2 1 5 6 7 0 8]


In [18]:
vector4 = np.zeros(10)
for i in range(0, vector.shape[0]):
    if i%2==1:
        vector4[i] = vector[i] * 2
    else:
        vector4[i] = vector[i]
print(vector4)

[ 1.  8.  5. 12.  2.  2.  5. 12.  7.  0.]


In [31]:
vector5 = vector[::-1]
print(vector5)

[0 7 6 5 1 2 6 5 4 1]


In [29]:
#zadanie 2
#mnożenie przez skalar
vec = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
skalar = 5
result = vec * skalar
print("Skalar mnoży każdą liczbę listy")
print(result)
#mnożenie dwóch list
vec2 = np.array([0, 2, 4, 6, 8, 10, 12, 14, 16])
result2 = vec * vec2
print("W dwóch listach liczby na tych saych indeksach mnożą się ze sobą")
print(result2)

Skalar mnoży każdą liczbę listy
[ 5 10 15 20 25 30 35 40 45]
W dwóch listach liczby na tych saych indeksach mnożą się ze sobą
[  0   4  12  24  40  60  84 112 144]


In [20]:
#zadanie 3
x = np.array([3, 5, 0, 2, 6, 1, 3, 8, 9]).reshape(3, 3)
x[0][0] = -2
x[1][1] = 44
x[-1][-1] = 0
x

array([[-2,  5,  0],
       [ 2, 44,  1],
       [ 3,  8,  0]])

In [21]:
#zadanie 4
for i in range(0, x.shape[0]):
    for j in range(0, x.shape[1]):
        if i%2==0 and j%2==0:
            x[i][j] = 0
x

array([[ 0,  5,  0],
       [ 2, 44,  1],
       [ 0,  8,  0]])

In [23]:
#zadanie 5
a = np.array([2, 1, 1, 1, 3, 6, 4, 5, 5]).reshape(3, 3)
b = np.array([1, 0, 5, 2, 1, 6, 0, 3, 0]).reshape(3, 3)
c = np.zeros((3, 3))
for i in range(0, a.shape[0]):
    for j in range(0, a.shape[1]):
        c[i][j] = a[i][j] + b[i][j]
c

array([[ 3.,  1.,  6.],
       [ 3.,  4., 12.],
       [ 4.,  8.,  5.]])

In [25]:
%pip install tensorflow

     -------------------------------------- 266.3/266.3 MB 5.2 MB/s eta 0:00:00
     ---------------------------------------- 57.5/57.5 kB ? eta 0:00:00
     ---------------------------------------- 65.5/65.5 kB ? eta 0:00:00
     ---------------------------------------- 3.7/3.7 MB 13.2 MB/s eta 0:00:00
     --------------------------------------- 23.2/23.2 MB 10.6 MB/s eta 0:00:00
     ------------------------------------- 895.9/895.9 kB 11.4 MB/s eta 0:00:00
     ---------------------------------------- 1.5/1.5 MB 13.4 MB/s eta 0:00:00
     -------------------------------------- 126.5/126.5 kB 7.3 MB/s eta 0:00:00
     ---------------------------------------- 6.0/6.0 MB 13.7 MB/s eta 0:00:00
     -------------------------------------- 439.2/439.2 kB 9.1 MB/s eta 0:00:00
     ---------------------------------------- 1.7/1.7 MB 15.2 MB/s eta 0:00:00
     ------------------------------------- 781.3/781.3 kB 12.2 MB/s eta 0:00:00
     ------------------------------------- 177.2/177.2 kB 

In [26]:
#zadanie 6
import tensorflow as tf
tensor = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(tensor)

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]], shape=(4, 4), dtype=int32)


In [32]:
#dim=2 (wymiar), rozmiar: 4x4, wartość typ: int